people/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'people'
urlpatterns = [
	path('', views.index, name='people'),
	path('login/', auth_views.LoginView.as_view(template_name='people/login.html')),
	path('logout/', auth_views.LogoutView.as_view(template_name='people/login.html')),
	path('apikey/', views.apikey, name='apikey'),
	path('mentees/', views.MenteesView.as_view(template_name='people/mentees_list.html'), name='mentees'),
	path('<str:username>/', views.profile, name='profile'),

]

touch/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from praise.api import PraiseResource
from people.api import UserResource

user_resource = UserResource()
praise_resource = PraiseResource()

urlpatterns = [
    path('people/', include('people.urls')),
    path('feedback/', include('feedback.urls')),
    path('praise/', include('praise.urls')),
    path('oauth2', include('social_django.urls', namespace='social')),
    path('api/v1/', include(user_resource.urls)),
    path('api/v1/', include(praise_resource.urls)),
    path('admin/', admin.site.urls),
    path('', include('people.urls')),
]

people/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Department(models.Model):
    name = models.CharField(max_length=100)
    lead = models.ForeignKey('User', on_delete=models.DO_NOTHING, related_name="lead")
    def __str__(self):
        return self.name

class User(AbstractUser):
    """
    A user of touch who will be using this system.
    """
    #XXX it was breaking oauth, we will redo user class anyway
    #department = models.ForeignKey(Department, default=0, on_delete=models.DO_NOTHING)
    is_active = models.BooleanField(default=True)
    mentor = models.ForeignKey('User', on_delete=models.DO_NOTHING, blank=True, null=True)

    def name(self):
        return self.first_name + ' ' + self.last_name

class Team(models.Model):
    name = models.CharField(max_length=100)
    people = models.ManyToManyField(User)
    reviewer = models.ForeignKey('User', on_delete=models.DO_NOTHING, related_name="reviewer", blank=True, null=True)
    def __str__(self):
        return self.name

people/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import User
from praise.models import Praise
from feedback.models import Response
from tastypie.models import ApiKey
from feedback.views import user_is_curator

@login_required
def index(request):
    context = {'users': User.objects.filter(is_active=True).order_by('first_name'), 'reviewer' : user_is_curator(request.user)}
    return render(request, 'people/index.html', context)

@login_required
def profile(request, username):
    person = User.objects.filter(username=username)[0]
    kudos = Praise.objects.filter(receiver=person.id)
    feedback = Response.objects.filter(receiver=person.id,public=True,ready=True)
    if person == request.user or person.mentor == request.user:
        feedback = feedback.union(Response.objects.filter(receiver=person.id))
    
    context = {'user' : request.user, 'person' : person, 'kudos' : kudos, 'feedback' : feedback, 'reviewer' : user_is_curator(request.user) }
    return render(request, 'people/profile.html', context)

@login_required
def apikey(request):
    user = User.objects.filter(username=request.user.username)[0]

    apikey = ApiKey.objects.filter(user=user)[0]
    
    context = {'user' : user, 'apikey' : apikey, 'reviewer' : user_is_curator(request.user) }
    return render(request, 'people/apikey.html', context)

class MenteesView(ListView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviewer'] = user_is_curator(self.request.user)
        return context

    def get_queryset(self):
        return User.objects.filter(mentor=self.request.user.id)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, 'You do not have the permission.')
            return HttpResponseNotFound('<h1>Page not found</h1>')
        return super(MenteesView, self).dispatch(request,*args, **kwargs)

people/templates/people/apikey.html
{% extends "base.html" %}
<title>touch:people</title>
{% block content %}
<section class="content">
    {% if apikey %}
        username: <strong>{{user.username}}</strong>
        <br />
        API Key: <strong>{{ apikey.key }}</strong>
     {% endif %}
  
</section>
{% endblock %}

people/templates/people/index.html
{% extends "base.html" %}
<title>touch:people</title>
{% block content %}
<section class="content">
	 <p>Hello, {{ user.first_name }}</p>
	 <p>Welcome to touch!</p>
	 <hr>
	 <h2>People</h2>
		{% for user in users %}
		  <p><a href="{% url 'people:profile' user.username %}">{{ user.name }}</a></p>
		{% endfor %}

</section>
{% endblock %}

people/templates/people/login.html
{% extends "base.html" %}
<title>touch</title>
{% block content %}
<section class="content">
	Login with <a href="{% url 'social:begin' 'phabricator' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}">Phabricator</a>
</section>
{% endblock %}

people/templates/people/mentees_list.html
{% extends "base.html" %}
<title>touch:people</title>
{% block content %}
<section class="content">
	 <h2>My mentees</h2>
        {% for user in user_list %}
        <li><a href="{% url 'people:profile' user.username %}">{{ user.name }}</a></li>
            {% empty %}
                <li>No mentees.</li>
        {% endfor %}

</section>
{% endblock %}

people/templates/people/profile.html
{% extends "base.html" %}
<title>touch:people</title>
{% block content %}
<section class="content">
     <h1>{{ person.name }}</h1>
     username: <strong>{{person.username}}</strong>
 
     <br />
     <br />
     <h2>Kudos</h2>
    {% for k in kudos %}
        <p>From <strong><a href="{% url 'people:profile' k.giver.username %}">{{ k.giver.name }}</a></strong>:</p>
        {{k.text}} <span style="color: #8c7c8e"> ({{k.timestamp}})</span>
    {% empty %}
         No kudos yet.
    {% endfor %}

    <h2>Feedback Received</h2>
    {% for f in feedback %}
        <p>From 
            {% if f.is_anon %}
                (ANONYMOUS)
            {% else %}                                                                
                <strong><a href="{% url 'people:profile' f.giver.username %}">{{ f.giver.name }}</a></strong>
			{% endif %}
            :
        </p> 
        {{f.text}} <span style="color: #8c7c8e"> ({{f.timestamp}})</span>
    {% empty %}
         No feedback yet.
    {% endfor %}
</section>
{% endblock %}