feedback/urls.py
from django.urls import path

from . import views

app_name = 'feedback'
urlpatterns = [
	path('', views.index, name='index'),
	path('done/', views.submit, name='done'),
	path('results/', views.ResultsView.as_view(template_name='feedback/results_list.html'), name='results'),
	path('results/<str:receiver>/', views.ReceiverView.as_view(), name='details'),
	path('review/', views.ReviewView.as_view(template_name='feedback/review_list.html'), name='review'),
	path('my/', views.MyView.as_view(template_name='feedback/my_list.html'), name='my'),
	path('edit/<int:id>', views.edit, name='edit'),
]

touch/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from praise.api import PraiseResource
from people.api import UserResource

user_resource = UserResource()
praise_resource = PraiseResource()

urlpatterns = [
    path('people/', include('people.urls')),
    path('feedback/', include('feedback.urls')),
    path('praise/', include('praise.urls')),
    path('oauth2', include('social_django.urls', namespace='social')),
    path('api/v1/', include(user_resource.urls)),
    path('api/v1/', include(praise_resource.urls)),
    path('admin/', admin.site.urls),
    path('', include('people.urls')),
]

feedback/models.py
from django.db import models
from people.models import User

class Response(models.Model):
    giver = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="feedback_giver")
    receiver = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="feedback_receiver")
    text = models.CharField(max_length=1000)
    is_anon = models.BooleanField(default=False)
    timestamp = models.DateTimeField('timestamp')
    ready = models.BooleanField(default=False)
    public = models.BooleanField(default=False)

    def __str__(self):
        return self.giver.username + "-" + self.receiver.username

feedback/forms.py
from django import forms

#XXX use Meta here?
class ResponseForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(), max_length=2000)
    is_anon = forms.BooleanField(required=False)

feedback/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic.list import ListView
from django.utils import timezone

from people.models import User, Department, Team
from .models import Response
from .forms import ResponseForm

#XXX not sure I like how we use is_curator as a context var to in the base.html menu
def user_is_curator(user):
    return user.is_staff or Team.objects.filter(reviewer=user.id).exists()

@login_required
def index(request):
    giver = request.user
    teams = Team.objects.filter(people__in=[giver])

    receivers = User.objects.none()
    for team in teams:
        receivers = receivers.union(team.people.exclude(username=giver.username))

    if Department.objects.filter(lead=giver.id):
        receivers = receivers.union(User.objects.filter(department=giver.department).exclude(username=giver.username))
    
    others = User.objects.filter(is_active=True).exclude(username=giver.username).difference(receivers).order_by('first_name')

    context = {'receivers': receivers, 'giver' : giver, 'others': others }
    context['reviewer'] = user_is_curator(request.user)
    return render(request, 'feedback/index.html', context)

@login_required
def submit(request):
    user = request.user
    for item in request.POST:
        receiver = User.objects.filter(username=item)
        if receiver:
            anon = item + "_anon"
            if anon in request.POST:
                is_anon = True
            else:
                is_anon = False
            if request.POST[item] != '':
                response = Response(giver=user, receiver=receiver[0],text=request.POST[item], is_anon=is_anon, timestamp=timezone.now())
                response.save()

    # should we have a try here
    context = {'giver' : user}
    context['reviewer'] = user_is_curator(user)
    return render(request, 'feedback/done.html', context)

#XXX I'm using is_staff as the field for the people who can see all the feedback from everyone
def responses_to_review(reviewer):
    responses = Response.objects.none()
    for response in Response.objects.filter(ready=False):
        if Team.objects.filter(people__in=[response.giver,response.receiver], reviewer=reviewer).exists() or reviewer.is_staff:
            responses = responses.union(Response.objects.filter(pk=response.id))
    return responses

class ResultsView(ListView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pending'] = responses_to_review(self.request.user).count()
        context['reviewer'] = user_is_curator(self.request.user)
        return context

    def get_queryset(self):
        people = User.objects.none()
        for response in Response.objects.filter(ready=True):
                people = people.union(User.objects.filter(pk=response.receiver.id))
        return people

    def dispatch(self, request, *args, **kwargs):
        if not user_is_curator(request.user):
            messages.error(request, 'You do not have the permission.')
            return HttpResponseNotFound('<h1>Page not found</h1>')
        return super(ResultsView, self).dispatch(request,*args, **kwargs)

class ReceiverView(ListView):
    model = Response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['receiver'] = self.receiver
        context['reviewer'] = user_is_curator(self.resquest.user)
        return context
     
    def get_queryset(self):
        self.receiver = get_object_or_404(User, username=self.kwargs['receiver'])
        return Response.objects.filter(receiver=self.receiver.id)

    def dispatch(self, request, *args, **kwargs):
        if not user_is_curator(request.user):
            messages.error(request, 'You do not have the permission.')
            return HttpResponseNotFound('<h1>Page not found</h1>')
        return super(ReceiverView, self).dispatch(request,*args, **kwargs)

class ReviewView(ListView):
    model = Response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviewer'] = user_is_curator(self.request.user)
        return context
     
    def get_queryset(self):
        return responses_to_review(self.request.user)

    def post(self, request, *args, **kwargs):
        # save feedback edit
        if request.POST:
            form = ResponseForm(request.POST)
            if form.is_valid():
                #XXX is there a better way to get the reponse id?
                response = Response.objects.filter(pk=request.POST['id'])[0]
                response.text = form.cleaned_data['text']
                response.is_anon = form.cleaned_data['is_anon']
                response.save()
        
        return redirect('/feedback/review/')

    def dispatch(self, request, *args, **kwargs):
        if not user_is_curator(request.user):
            messages.error(request, 'You do not have the permission.')
            return HttpResponseNotFound('<h1>Page not found</h1>')
        
        # approve response #XXX this could be done better - in REST?
        if request.GET and 'id' in request.GET.keys():
            response = Response.objects.filter(pk=request.GET['id'])[0]
            response.ready = True
            response.save()

        return super(ReviewView, self).dispatch(request, *args, **kwargs)

class MyView(ListView):
    model = Response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviewer'] = user_is_curator(self.request.user)
        return context
     
    def get_queryset(self):
        return Response.objects.filter(receiver=self.request.user.id,ready=True)

    def dispatch(self, request, *args, **kwargs):
        # approve response #XXX this could be done better - in REST?
        if request.GET and 'id' in request.GET.keys():
            response = Response.objects.filter(pk=request.GET['id'])[0]
            if (request.user == response.receiver):
                response.public = not response.public
                response.save()
        
        return super(MyView, self).dispatch(request, *args, **kwargs)

@login_required
def edit(request, id):
    if not user_is_curator(request.user):
        return HttpResponseNotFound('<h1>Page not found</h1>')

    response = Response.objects.filter(pk=id)[0]

    form = ResponseForm()
    form.fields['text'].initial = response.text
    form.fields['is_anon'].initial = response.is_anon

    context = {'response': response, 'form' : form}
    context['reviewer'] = user_is_curator(request.user)
    return render(request, 'feedback/edit.html', context)

feedback/templates/feedback/done.html
{% extends "base.html" %}
<title>touch:feedback</title>
{% block content %}
<section class="content">
<h1>Thank you for the submission, {{ giver.first_name }}</h1>
</section>
{% endblock %}

feedback/templates/feedback/edit.html
{% extends "base.html" %}
<title>touch:feedback</title>
{% block content %}
<section class="content">
<h2> Feedback from <strong>{{response.giver.name}}</strong> to <strong>{{response.receiver.name}}</strong> </h2>
{{ response.timestamp }}
<form id="form-feedback-edit" action="{% url 'feedback:review' %}" method="post">
    {% csrf_token %}
    <input type="hidden" value="{{ response.id }}" name="id">
    {{ form.text }}
    <br />
    {{ form.is_anon }}  Is the feedback anonymous?
    <br />
	<input class="btn-submit" type="submit" value="Save">
      </form>
</section>
{% endblock %}

feedback/templates/feedback/index.html
{% extends "base.html" %}
{% load static %}
<title>touch:feedback</title>

{% block content %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!-- Select2 component -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script src="{% static 'js/main.js' %}"></script>

  <section class="content">
    <p>
    Hello, {{giver.first_name}},
    </p>
    <p>
    Welcome to <strong>touch &#x2764;</strong>. You can use <strong>touch &#x2764;</strong> to give feedback to your colleagues.
    </p>

    <p>
	(WARNING! Feel free to use the form, but this is still experimental and was created for the 360 feedback pilot in the Google Projects. Any feedback you put here will read by Gustavo Padovan and Olivier Potin. The goal is to curate it so we all can learn how to give _real_ constructive feedback. Once reviewed, the receiver will be able to see the feedback)
    </p>
    <p>
    The guidelines below will help you give praise and/or suggestions for improvement to the people you work with. You only need to give feedback where you have comments or suggestions for a person in a specific area. There's no need to give feedback for everyone, and no need to go through every single area listed below.
 
    </p>

    <ul>
	    <li><strong>Technical Ability</strong> - How is the person taking on their tasks? What is good? What could improve?</li>
      <li><strong>Communication</strong> - Has the person communicated their progress well? Are their status reports articulated well? Straight to the point? What could they improve?</li>
      <li><strong>Customer Relationship</strong> - If the person had any interaction with the customer, did they do a good job? Any improvement needed?</li>
      <li><strong>Project Management</strong> - How is the person tracking their work? Has the person delivered as per the project's expectations in terms of quality and timeline?</li>
      <li><strong>Open Source Citizenship</strong> - If the person had any interaction with the community, did they do a good job? What could be better?</li>
      <li><strong>Enablement</strong> - Does the person help to enable the work of others? What could improve?</li>
    </ul>

<p>Remember:</p>
    <ul>
	    <li>Don't spend more than 2-5 minutes per person, let's keep this as lightweight as possible.</li>
	    <li>Your feedback will be shared with the person!</li>
	    <li>You can give feedback to more people by adding them through the select box at the end.</li>
	    <li>You can make your feedback anonymous by ticking the checkbox after the name of each person. The Feedback Owner (padovan) will be be able to see it is from you, but it will be anonymous to the receiver.</li>

 <li>For a nice read on how to give good feedback see this <a href="
 https://medium.com/google-design/the-art-of-giving-feedback-80a6a4e2e843">article</a>.</li>
    </ul>
<p>Thank you.</p>
<p>--</p>
    <form id="form-feedbacks" action="{% url 'feedback:done' %}" method="post">
        {% csrf_token %}

  
        <div id="new-feedbacks"></div>
  
        <p>Select the people you want to give feedback to:</p>
        <span class="hot-feedback" value="{{giver.username}}">Self</span>

        {% for person in receivers %}
          <span class="hot-feedback" value="{{ person.username }}">{{person.name}}</span>
        {% endfor %}

        <br />
        <div class="select-feedback">
          <p>More people:</p>

          <select id="add-feedback" name="new-feedback">
            <option></option>
            {% for person in others %}
              <option id="opt-{{ person.username }}" value="{{ person.username }}">{{ person.name }}</option>
            {% endfor %}
          </select>
        </div>
        <footer>
          <input class="btn-submit" type="submit" value="Submit">
        </footer>

      </form>
  </section>
{% endblock %}

feedback/templates/feedback/my_list.html
{% extends "base.html" %}
<title>touch:feedback</title>
{% block content %}
<section class="content">
	<h2> Feedback for {{request.user.name}} </h2>
	{% for response in response_list %}
	 	    <p>From 
            {% if response.is_anon %}
                (ANONYMOUS)
            {% else %}                                                                
                <strong>{{ response.giver.name }}</strong>
			{% endif %}
			:
			</p>
			<p>{{response.text}} <span style="color: #8c7c8e"> ({{response.timestamp}})</span></p>
			{% if response.public  %}
				<a href="/feedback/my/?id={{ response.id }}">Make it private</a>
			{% else %}
				<a href="/feedback/my/?id={{ response.id }}">Make it public</a>
			{% endif %}
			<br />
	{% empty %}
		<p>No responses yet.</p>
	{% endfor %}
</section>
{% endblock %}

feedback/templates/feedback/response_list.html
{% extends "base.html" %}
<title>touch:feedback</title>
{% block content %}
<section class="content">
	<h2> Feedback for {{receiver.name}} </h2>
	{% for response in response_list %}
		{% if response.text != '' %}
	 	        <p>From <strong>{{ response.giver.name }}</strong>
			{% if response.is_anon %}
				(ANONYMOUS)
			{% endif %}
			:
			</p>
			<p>{{response.text}} <span style="color: #8c7c8e"> ({{response.timestamp}})</span></p>
			<br />
			
		{% endif %}
	{% empty %}
		<p>No responses yet.</p>
	{% endfor %}
</section>
{% endblock %}

feedback/templates/feedback/results_list.html
{% extends "base.html" %}
<title>touch:feedback</title>
{% block content %}
<section class="content">
<h1>Results</h1>

You have <a href="/feedback/review/"> {{ pending }}  feedback{% if pending > 1 %}s{% endif %}</a> to review.

<h4>Feedack Curated:</h4>

<ul>
	{% for user in user_list %}
	<li><a href="{{user.username}}/">{{ user.name }}</a></li>
	    {% empty %}
	        <li>No responses yet.</li>
		{% endfor %}
</ul>
</section>
{% endblock %}

feedback/templates/feedback/review_list.html
{% extends "base.html" %}
<title>touch:feedback</title>
{% block content %}
<section class="content">
	<h2> Feedback for Curation</h2>
	{% for response in response_list %}
		{% if response.text != '' %}
	 	        <p>From <strong>{{ response.giver.name }}</strong> to <strong>{{ response.receiver.name }}</strong>
			{% if response.is_anon %} (ANONYMOUS) {% endif %}
			:
			</p>
			<p>{{response.text}} <span style="color: #8c7c8e"> ({{response.timestamp}})</span></p>
			<a href="/feedback/review/?id={{ response.id }}">Approve</a>
			<a href="/feedback/edit/{{ response.id }}">Edit</a>
			<hr>
			<br />
			
		{% endif %}
	{% empty %}
		<p>No feedback to curate.</p>
	{% endfor %}
</section>
{% endblock %}